### ISSUE TITLE
use pyflw error: ModuleNotFoundError: No module named 'ucis.ucdb'

### ISSUE THREAD

**Issue by Damien-Wu** [chipsalliance/riscv-dv#940]
When I use  sudo python3 run.py --test=riscv_arithmetic_basic_test  --simulator=pyflow:

Wed, 19 Jul 2023 11:11:57 INFO     Creating output directory: out_2023-07-19
Wed, 19 Jul 2023 11:11:57 INFO     Processing regression test list : /home/wh/RISCV_DV/riscv-dv/target/rv32imc/testlist.yaml, test: riscv_arithmetic_basic_test
Wed, 19 Jul 2023 11:11:57 INFO     Processing regression test list : /home/wh/RISCV_DV/riscv-dv/yaml/base_testlist.yaml, test: riscv_arithmetic_basic_test
Wed, 19 Jul 2023 11:11:57 INFO     Found matched tests: riscv_arithmetic_basic_test, iterations:2
Wed, 19 Jul 2023 11:11:57 INFO     Processing simulator setup file : /home/wh/RISCV_DV/riscv-dv/yaml/simulator.yaml
Wed, 19 Jul 2023 11:11:57 INFO     Found matching simulator: pyflow
Wed, 19 Jul 2023 11:11:57 INFO     Building RISC-V instruction generator
Wed, 19 Jul 2023 11:11:57 INFO     Running RISC-V instruction generator
Wed, 19 Jul 2023 11:11:57 INFO     Generating 2 riscv_arithmetic_basic_test
Wed, 19 Jul 2023 11:11:57 INFO     Running riscv_arithmetic_basic_test with 1 batches
Wed, 19 Jul 2023 11:11:57 INFO     Running riscv_arithmetic_basic_test, batch 1/1, test_cnt:2
Wed, 19 Jul 2023 11:11:58 INFO     Traceback (most recent call last):
  File "/home/wh/RISCV_DV/riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py", line 20, in <module>
    from pygen_src.riscv_instr_pkg import *
  File "/home/wh/RISCV_DV/riscv-dv/pygen/pygen_src/riscv_instr_pkg.py", line 14, in <module>
    import vsc
  File "/home/wh/.local/lib/python3.8/site-packages/vsc/__init__.py", line 42, in <module>
    from ucis.ucdb.ucdb_factory import UcdbFactory
ModuleNotFoundError: No module named 'ucis.ucdb'

Wed, 19 Jul 2023 11:11:58 ERROR    ERROR return code: True/1, cmd: python3 /home/wh/RISCV_DV/riscv-dv/pygen/pygen_src/test/riscv_instr_base_test.py --num_of_tests=2 --start_idx=0 --asm_file_name=out_2023-07-19/asm_test/riscv_arithmetic_basic_test --log_file_name=out_2023-07-19/sim_riscv_arithmetic_basic_test_0.log  --target=rv32imc  --gen_test=riscv_instr_base_test  --seed=821489154 --instr_cnt=10000 --num_of_sub_program=0 --directed_instr_0=riscv_int_numeric_corner_stream,4 --no_fence=1 --no_data_page=1 --no_branch_jump=1 --boot_mode=m --no_csr_instr=1

**Comment by ShraddhaDevaiya** [comment]
Hi @Damien-Wu , can you try to install UCIS with this command: `pip install pyEDAA.UCIS`
 
and then try to run your command. Not sure, but might resolve it.
